window.PRAISES = [
    { he: "וואו! אתה אלוף האלופים!", en: "Wow! ata aluf ha-alufim!" },
    { he: "כל הכבוד! המוח שלך עובד שעות נוספות!", en: "Kol ha-kavod! ha-moach shelcha oved sha'ot nosafot!" },
    { he: "איזה גאון! אפשר לקבל ממך חתימה?", en: "Eize ga'on! efshar lekabel mimcha chatima?" },
    { he: "מעולה! אפילו הדגים בים מחאו כפיים!", en: "Me'ule! afilu ha-dagim ba-yam mach'u kapayim!" },
    { he: "פצצה! אתה חד כמו סכין!", en: "Ptzatza! ata chad kmo sakin!" },
    { he: "יאללה! אתה טס כמו טיל!", en: "Yalla! ata tas kmo til!" },
    { he: "אלוף! סבתא שלך גאה בך בטירוף!", en: "Aluf! Savta shelcha ge'a becha be-tiruf!" },
    { he: "מדהים! התוכי של השכן למד ממך לדבר!", en: "Madhim! ha-tuki shel ha-shachen lamad mimcha ledaber!" },
    { he: "כל הכבוד! הגעת לרמה של אלוף העולם באותיות!", en: "Kol ha-kavod! higata le-rama shel aluf ha-olam ba-otiot!" },
    { he: "וואו! אתה מהיר כמו ברק!", en: "Wow! ata mahir kmo barak!" },
    { he: "מושלם! אין עליך בעולם!", en: "Mushlam! ein alecha ba-olam!" },
    { he: "חזק! אתה שובר את הכלים!", en: "Chazak! ata shover et ha-kelim!" },
    { he: "אשש! אתה חכם כמו שלמה המלך!", en: "Ash! ata chacham kmo Shlomo ha-Melech!" },
    { he: "בום! אתה מטפס על הקירות מרוב כישרון!", en: "Bum! ata metapes al ha-kirot merov kisharon!" },
    { he: "גדול! אתה הכוכב של הרגע!", en: "Gadol! ata ha-kochav shel ha-rega!" },
    { he: "סחתיין! אפילו החתול מתלהב ממך!", en: "Sachteyn! afilu ha-chatul mitlahev mimcha!" },
    { he: "מלך! אתה לא עוצר אף פעם!", en: "Melech! ata lo otzer af pa'am!" },
    { he: "מטורף! שבע ברצף, אין דברים כאלה!", en: "Metoraf! sheva beretzef, ein dvarim ka-ele!" },
    { he: "כל הכבוד! אתה מרגיש כמו אחרי מקלחת קרה!", en: "Kol ha-kavod! ata margish kmo achare miklachat kara!" },
    { he: "גאוני! אתה בטח קראת את כל המילון!", en: "Ga'oni! ata betach karata et kol ha-milon!" },
    { he: "וואו! אתה לומד אותיות מהר יותר מהמורה!", en: "Wow! ata lomed otiot maher yoter mehamore!" },
    { he: "כל הכבוד! הראש שלך מלא אותיות ולא עגבניות!", en: "Kol hakavod! harosh shelcha male otiot velo agvaniyot!" },
    { he: "איזה כישרון! אתה מזהה אותיות גם בחלום!", en: "Eize kisharon! ata mezahe otiot gam bachalom!" },
    { he: "מעולה! האותיות מפחדות ממך!", en: "Me'ule! ha'otiot mefachadot mimcha!" },
    { he: "פצצה! אתה קורא כמו רובוט על קפה!", en: "Ptzatza! ata kore kmo robot al kafe!" },
    { he: "יאללה! עוד אות ופותחים חגיגה!", en: "Yalla! od ot u'potchim chagiga!" },
    { he: "אלוף! אפילו הקנגורו מקנא בקפיצות שלך!", en: "Aluf! afilu hakanguru mekane bakfitzot shelcha!" },
    { he: "מדהים! אתה חד כמו פלפל חריף!", en: "Madhim! ata chad kmo pilpel charif!" },
    { he: "כל הכבוד! אתה מנצח אותיות כמו במשחק מחשב!", en: "Kol hakavod! ata menatzeach otiot kmo bemischak machshev!" },
    { he: "וואו! המוח שלך הוא מחשב-על קטן!", en: "Wow! hamoach shelcha hu machshev-al katan!" },
    { he: "מושלם! אם היו נותנים מדליה, היית מקבל זהב!", en: "Mushlam! im hayu notnim medalya, hayita mekabel zahav!" },
    { he: "חזק! אתה חזק יותר מפיל עם משקולות!", en: "Chazak! ata chazak yoter mafil im mishkulot!" },
    { he: "אשש! חכמה כזאת עוד לא ראיתי!", en: "Ash! chochma kazot od lo ra'iti!" },
    { he: "בום! האותיות עפות לך מהראש כמו זיקוקים!", en: "Bum! ha'otiot afot lecha meharosh kmo zikukim!" },
    { he: "גדול! אתה ממש כוכב טלוויזיה!", en: "Gadol! ata mamash kochav televizya!" },
    { he: "סחתיין! אפילו הדודה מרוצה ממך, וזה נדיר!", en: "Sachteyn! afilu hadoda merutza mimcha, veze nadir!" },
    { he: "מלך! אתה מושל בממלכת האותיות!", en: "Melech! ata moshel bemamlachat ha'otiot!" },
    { he: "מטורף! אתה עונה נכון עוד לפני השאלה!", en: "Metoraf! ata oneh nachon od lifnei hashe'ela!" },
    { he: "כל הכבוד! אתה מפצח אותיות כמו אגוזים!", en: "Kol hakavod! ata mefacheach otiot kmo egozim!" },
    { he: "גאוני! המורה שלך צריכה ללמוד ממך!", en: "Ga'oni! hamore shelcha tzricha lilmod mimcha!" },
    { he: "וואו! אתה מהיר כמו ווי-פיי טוב!", en: "Wow! ata mahir kmo wifi tov!" },
    { he: "איזה אלוף! האותיות מסתדרות לך בתור!", en: "Eize aluf! ha'otiot mistadrot lecha betor!" },
    { he: "מעולה! אתה חד יותר מעיפרון מחודד!", en: "Me'ule! ata chad yoter me'iparon mechudad!" },
    { he: "פצצה! אתה מצליח כמו סופרמן בבוקר!", en: "Ptzatza! ata matzliach kmo Superman baboker!" },
    { he: "יאללה! עוד קצת ואתה קורא ספר שלם!", en: "Yalla! od ktzat ve'ata kore sefer shalem!" },
    { he: "אלוף! אתה שולט באותיות ביד אחת!", en: "Aluf! ata sholet ba'otiot beyad achat!" },
    { he: "מדהים! אפילו הרובוטים מחאו לך כפיים!", en: "Madhim! afilu harobotim mach'u lecha kapayim!" },
    { he: "כל הכבוד! אתה פותר אותיות כמו חידות קלות!", en: "Kol hakavod! ata pater otiot kmo chidot kalot!" },
    { he: "וואו! אתה מבריק כמו נורה של מיליון וואט!", en: "Wow! ata mavrik kmo nura shel milyon wat!" },
    { he: "מושלם! אתה כוכב העל של האותיות!", en: "Mushlam! ata kochav ha'al shel ha'otiot!" },
    { he: "חזק! אתה עונה כמו מכונה מדויקת!", en: "Chazak! ata oneh kmo mechona meduyeket!" },
    { he: "אשש! אתה חכם כמו אנציקלופדיה מהלכת!", en: "Ash! ata chacham kmo entziklopedia mehalechet!" },
    { he: "בום! אתה מנצח בלי להזיע בכלל!", en: "Bum! ata menatzeach bli lehazia bikhlal!" },
    { he: "גדול! האותיות מוחאות לך כפיים!", en: "Gadol! ha'otiot moch'ot lecha kapayim!" },
    { he: "סחתיין! אתה מקסים כמו גור כלבים!", en: "Sachteyn! ata maksim kmo gur klavim!" },
    { he: "מלך! אתה שולט בלי חרב, רק עם הראש!", en: "Melech! ata sholet bli cherev, rak im harosh!" },
    { he: "מטורף! אתה לומד בזמן שאחרים מפהקים!", en: "Metoraf! ata lomed bizman she'acherim mefa'akim!" },
    { he: "כל הכבוד! אתה חד כתער של ספר!", en: "Kol hakavod! ata chad keta'ar shel sofer!" },
    { he: "גאוני! אתה יודע אותיות יותר טוב מהמילון!", en: "Ga'oni! ata yodea otiot yoter tov mehamilon!" },
    { he: "וואו! אתה טס קדימה כמו רכבת מהירה!", en: "Wow! ata tas kadima kmo rakevet mehira!" },
    { he: "איזה אלוף! אתה מנצח את המשחק בלי מאמץ!", en: "Eize aluf! ata menatzeach et hamischak bli ma'amatz!" },
    { he: "מעולה! אתה נוצץ כמו יהלום בלילה!", en: "Me'ule! ata notzetz kmo yahalom balayla!" },
    { he: "פצצה! אתה עונה מהר כמו ברק כפול!", en: "Ptzatza! ata oneh maher kmo barak kaful!" },
    { he: "יאללה! האותיות מחכות לך בתור!", en: "Yalla! ha'otiot mechakot lecha betor!" },
    { he: "אלוף! אתה לומד כמו ספוג ששותה מים!", en: "Aluf! ata lomed kmo sfog sheshote mayim!" },
    { he: "מדהים! אתה זוכר אותיות יותר טוב מהפיל!", en: "Madhim! ata zocher otiot yoter tov mehapil!" },
    { he: "כל הכבוד! אתה ממשיך לנצח כאילו זה קל!", en: "Kol hakavod! ata mamshich lenatzeach ke'ilu ze kal!" },
    { he: "וואו! אתה מבריק יותר מהירח המלא!", en: "Wow! ata mavrik yoter mehayareach hamale!" },
    { he: "מושלם! אין לך טעות אחת, כאילו אתה מחשב!", en: "Mushlam! ein lecha ta'ut achat, ke'ilu ata machshev!" },
    { he: "חזק! אתה עומד איתן כמו חומה!", en: "Chazak! ata omed eitan kmo choma!" },
    { he: "אשש! אתה ערמומי כמו שועל קטן וחכם!", en: "Ash! ata armumi kmo shual katan vechacham!" },
    { he: "בום! האותיות נכנעות בפניך!", en: "Bum! ha'otiot nichna'ot lefanecha!" },
    { he: "גדול! אתה נראה כמו גיבור-על עם גלימה!", en: "Gadol! ata nire kmo gibor-al im glima!" },
    { he: "סחתיין! אפילו התינוק של השכנים מתלהב!", en: "Sachteyn! afilu hatinok shel hashchenim mitlahev!" },
    { he: "מלך! אתה מנצח בלי לעצור בכלל!", en: "Melech! ata menatzeach bli la'atzor bikhlal!" },
    { he: "מטורף! אתה מהיר יותר מקליק של עכבר!", en: "Metoraf! ata mahir yoter miklik shel achbar!" },
    { he: "כל הכבוד! אתה פותר אותיות כמו שוקולד חם!", en: "Kol hakavod! ata pater otiot kmo shokolad cham!" },
    { he: "גאוני! הראש שלך הוא מכונת חידות!", en: "Ga'oni! harosh shelcha hu mechonat chidot!" },
    { he: "וואו! אתה לומד עם חיוך כזה שמידבק!", en: "Wow! ata lomed im chiyuch kaze shemidabek!" },
    { he: "איזה אלוף! אתה עונה כמו פזמון מוכר!", en: "Eize aluf! ata oneh kmo paamon mukar!" },
    { he: "מעולה! אתה זוהר כמו כוכב על במה!", en: "Me'ule! ata zohar kmo kochav al bama!" },
    { he: "פצצה! אתה חד כמו טיל בליסטי של ידע!", en: "Ptzatza! ata chad kmo til balisti shel yeda!" },
    { he: "יאללה! עוד ניצחון ותלווה אותך תשואות!", en: "Yalla! od nitzachon vetilve otcha tishu'ot!" },
    { he: "אלוף! אתה מנצח אותיות בלי להסתכל בכלל!", en: "Aluf! ata menatzeach otiot bli lehistakel bikhlal!" },
    { he: "מדהים! אתה חכם כמו עשרה פרופסורים!", en: "Madhim! ata chacham kmo asara profesorim!" },
    { he: "כל הכבוד! אתה ממשיך בדרך הנכונה, ישר!", en: "Kol hakavod! ata mamshich baderech hanchona, yashar!" },
    { he: "וואו! אתה נוצץ כמו שמש בקיץ!", en: "Wow! ata notzetz kmo shemesh bakayitz!" },
    { he: "מושלם! אתה מדויק כמו שעון שווייצרי!", en: "Mushlam! ata meduyak kmo sha'on shvaitzeri!" },
    { he: "חזק! אתה מגניב כמו סוכן חשאי!", en: "Chazak! ata magniv kmo sochen chashai!" },
    { he: "אשש! אתה ערני כמו חתול בלילה!", en: "Ash! ata erani kmo chatul balayla!" },
    { he: "בום! אתה מפוצץ את לוח האותיות!", en: "Bum! ata mefutzatz et luach ha'otiot!" },
    { he: "גדול! אתה גדול יותר מפיצה משפחתית!", en: "Gadol! ata gadol yoter mipitza mishpachtit!" },
    { he: "סחתיין! אתה מקסים כמו מכתב אהבה!", en: "Sachteyn! ata maksim kmo michtav ahava!" },
    { he: "מלך! אתה שולט באותיות כמו בקוביות!", en: "Melech! ata sholet ba'otiot kmo bekubiyot!" },
    { he: "מטורף! אתה לומד כל כך מהר שזה לא חוקי!", en: "Metoraf! ata lomed kol kach maher sheze lo chok!" },
    { he: "כל הכבוד! אתה מגלה אותיות כמו אוצר!", en: "Kol hakavod! ata megale otiot kmo otzar!" },
    { he: "גאוני! אתה בטח בנית את האותיות בעצמך!", en: "Ga'oni! ata betach banita et ha'otiot be'atzmecha!" },
    { he: "וואו! אתה מתקדם כמו רמזור ירוק!", en: "Wow! ata mitkadem kmo ramzor yarok!" },
    { he: "איזה אלוף! אתה עונה בביטחון של נינג'ה!", en: "Eize aluf! ata oneh bevitachon shel ninja!" },
    { he: "מעולה! אתה מבריק כמו פנס בערפל!", en: "Me'ule! ata mavrik kmo panas ba'arafel!" },
    { he: "פצצה! אתה עולה על כל ציפייה!", en: "Ptzatza! ata oleh al kol tzipiya!" },
    { he: "יאללה! עוד רגע ואתה אלוף העולם!", en: "Yalla! od rega ve'ata aluf ha'olam!" },
    { he: "אלוף! אתה מחזיק את האותיות בכיס!", en: "Aluf! ata machzik et ha'otiot bakis!" },
    { he: "מדהים! אתה חד כמו חרב סמוראי!", en: "Madhim! ata chad kmo cherev samurai!" },
    { he: "כל הכבוד! אתה מנצח כמו לוחם אמיץ!", en: "Kol hakavod! ata menatzeach kmo lochem amitz!" },
    { he: "וואו! אתה מהיר כמו קנגורו על קפיצים!", en: "Wow! ata mahir kmo kanguru al kfitzim!" },
    { he: "מושלם! אתה מושלם כמו ירח בערב!", en: "Mushlam! ata mushlam kmo yareach ba'erev!" },
    { he: "חזק! אתה חזק כמו אריה רעב לצחוק!", en: "Chazak! ata chazak kmo ari ra'ev litzchok!" },
    { he: "אשש! אתה חכם כמו ראש ממשלה, אבל נחמד!", en: "Ash! ata chacham kmo rosh memshala, aval nechmad!" },
    { he: "בום! אתה מפוצץ שיאים כל שנייה!", en: "Bum! ata mefutzatz shi'im kol shniya!" },
    { he: "גדול! אתה כוכב כמו בסרט הוליוודי!", en: "Gadol! ata kochav kmo beseret Hollywood!" },
    { he: "סחתיין! אתה מקסים כמו גלידה בקיץ!", en: "Sachteyn! ata maksim kmo glida bakayitz!" },
    { he: "מלך! אתה מנצח כמו מלך בלי ויתורים!", en: "Melech! ata menatzeach kmo melech bli viturim!" },
    { he: "מטורף! אתה עונה נכון גם בעיניים עצומות!", en: "Metoraf! ata oneh nachon gam be'einayim atzumot!" },
    { he: "כל הכבוד! אתה לומד כמו דבורה חרוצה!", en: "Kol hakavod! ata lomed kmo dvora charutza!" },
    { he: "גאוני! אתה מחשב אותיות כמו מחשבון!", en: "Ga'oni! ata mechashav otiot kmo machshevon!" },
    { he: "וואו! אתה מתקדם כמו רכבת הרים!", en: "Wow! ata mitkadem kmo rakevet harim!" },
    { he: "איזה אלוף! אתה עונה כמו הד של עצמך!", en: "Eize aluf! ata oneh kmo hed shel atzmecha!" },
    { he: "מעולה! אתה זוהר כמו נורות של במה!", en: "Me'ule! ata zohar kmo nerot shel bama!" },
    { he: "פצצה! אתה חד כמו קוץ של שושנה!", en: "Ptzatza! ata chad kmo kotz shel shoshana!" },
    { he: "יאללה! עוד אות וכובשים את העולם!", en: "Yalla! od ot ve'kochshim et ha'olam!" },
    { he: "אלוף! אתה מחזיק את הראש גבוה כמו ג'ירפה!", en: "Aluf! ata machzik et harosh gavoa kmo girafa!" },
    { he: "מדהים! אתה מהיר כמו דולפין בים!", en: "Madhim! ata mahir kmo dolfin bayam!" },
    { he: "כל הכבוד! אתה ממשיך לנצח כמו מכונה!", en: "Kol hakavod! ata mamshich lenatzeach kmo mechona!" },
    { he: "וואו! אתה נוצץ כמו כסף נקי!", en: "Wow! ata notzetz kmo kesef naki!" },
    { he: "מושלם! אתה מדויק כמו חץ של קשת!", en: "Mushlam! ata meduyak kmo chetz shel keshet!" },
    { he: "חזק! אתה אמיץ כמו לוחם במדבר!", en: "Chazak! ata amitz kmo lochem bamidbar!" },
    { he: "אשש! אתה פיקח כמו סבתא שמוצאת ממתקים!", en: "Ash! ata pikeach kmo savta shemotzet mimtakim!" },
    { he: "בום! אתה מפוצץ את המסך בכישרון!", en: "Bum! ata mefutzatz et hamasach bekisharon!" },
    { he: "גדול! אתה כוכב כמו שמש באמצע היום!", en: "Gadol! ata kochav kmo shemesh be'emtza hayom!" },
    { he: "סחתיין! אתה מקסים כמו חתלתול עם פפיון!", en: "Sachteyn! ata maksim kmo chatultul im papiyon!" },
    { he: "מלך! אתה שולט כמו קפטן על ספינה!", en: "Melech! ata sholet kmo kapitan al sfina!" },
    { he: "מטורף! אתה לומד כמו טיל משוגר!", en: "Metoraf! ata lomed kmo til meshugar!" },
    { he: "כל הכבוד! אתה פותר אותיות כמו סודוקו!", en: "Kol hakavod! ata pater otiot kmo sudoku!" },
    { he: "גאוני! אתה חכם כמו כל הספרים ביחד!", en: "Ga'oni! ata chacham kmo kol hasfarim beyachad!" },
    { he: "וואו! אתה מתקדם כמו סוס דוהר!", en: "Wow! ata mitkadem kmo sus doher!" },
    { he: "איזה אלוף! אתה עונה כמו מקהלה מסונכרנת!", en: "Eize aluf! ata oneh kmo mak'hela mesunchranet!" },
    { he: "מעולה! אתה זוהר כמו יהלום על טבעת!", en: "Me'ule! ata zohar kmo yahalom al taba'at!" },
    { he: "פצצה! אתה חד כמו זכוכית מגדלת!", en: "Ptzatza! ata chad kmo zchuchit magdelet!" },
    { he: "יאללה! עוד ניצחון ועוד אחד, יאללה!", en: "Yalla! od nitzachon ve'od echad, yalla!" },
    { he: "אלוף! אתה מחזיק מעמד כמו סלע בים!", en: "Aluf! ata machzik ma'amad kmo sela bayam!" },
    { he: "מדהים! אתה מהיר כמו סנונית באביב!", en: "Madhim! ata mahir kmo snunit ba'aviv!" },
    { he: "כל הכבוד! אתה ממשיך כמו כדור שלג!", en: "Kol hakavod! ata mamshich kmo kadur sheleg!" },
    { he: "וואו! אתה נוצץ כמו פנינה יקרה!", en: "Wow! ata notzetz kmo pnina yekara!" },
    { he: "מושלם! אתה מדויק כמו מנתח במשחק!", en: "Mushlam! ata meduyak kmo menateach bemischak!" },
    { he: "חזק! אתה איתן כמו הר געש!", en: "Chazak! ata eitan kmo har ga'ash!" },
    { he: "אשש! אתה ערמומי כמו חתול שמשיג אוכל!", en: "Ash! ata armumi kmo chatul shemasig ochel!" },
    { he: "בום! אתה מפוצץ את לוח הניקוד!", en: "Bum! ata mefutzatz et luach hanikud!" },
    { he: "גדול! אתה כוכב כמו גלקסיה שלמה!", en: "Gadol! ata kochav kmo galaksya shlema!" },
    { he: "סחתיין! אתה מקסים כמו פרח באביב!", en: "Sachteyn! ata maksim kmo perach ba'aviv!" },
    { he: "מלך! אתה מושל כמו קיסר רומא!", en: "Melech! ata moshel kmo kesar Roma!" },
    { he: "מטורף! אתה עונה כמו רובוט מהיר!", en: "Metoraf! ata oneh kmo robot mahir!" },
    { he: "כל הכבוד! אתה לומד כמו מנוע טורבו!", en: "Kol hakavod! ata lomed kmo mnu'a turbo!" },
    { he: "גאוני! אתה מחשב מהר כמו גיליון אלקטרוני!", en: "Ga'oni! ata mechashav maher kmo gilyon elektroni!" },
    { he: "וואו! אתה מתקדם כמו דג מנווט בזרם!", en: "Wow! ata mitkadem kmo dag menatev bazerem!" },
    { he: "איזה אלוף! אתה עונה כמו מורה פרטי!", en: "Eize aluf! ata oneh kmo more prati!" },
    { he: "מעולה! אתה זוהר כמו חנוכייה בלילה!", en: "Me'ule! ata zohar kmo chanukiya balayla!" },
    { he: "פצצה! אתה חד כמו לייזר מתקדם!", en: "Ptzatza! ata chad kmo laizer mitkadem!" },
    { he: "יאללה! עוד אות ופותחים במחולות!", en: "Yalla! od ot u'potchim bemacholot!" },
    { he: "אלוף! אתה מחזיק את הקצב כמו מתופף!", en: "Aluf! ata machzik et hakatzev kmo metofef!" },
    { he: "מדהים! אתה מהיר כמו רכב ספורט אדום!", en: "Madhim! ata mahir kmo rechev sport adom!" },
    { he: "כל הכבוד! אתה ממשיך בלי לעצור לתדלק!", en: "Kol hakavod! ata mamshich bli la'atzor letadlek!" },
    { he: "וואו! אתה נוצץ כמו כוכב נופל!", en: "Wow! ata notzetz kmo kochav nofel!" },
    { he: "מושלם! אתה מדויק כמו דקות של שעון!", en: "Mushlam! ata meduyak kmo dakot shel sha'on!" },
    { he: "חזק! אתה חזק כמו סופה בים!", en: "Chazak! ata chazak kmo sufa bayam!" },
    { he: "אשש! אתה חכם כמו מחשב עם מסך כפול!", en: "Ash! ata chacham kmo machshev im masach kaful!" },
    { he: "בום! אתה מפוצץ תשואות בכל פינה!", en: "Bum! ata mefutzatz tishu'ot bechol pina!" },
    { he: "גדול! אתה כוכב כמו זיקוק בשמיים!", en: "Gadol! ata kochav kmo zikuk bashamayim!" },
    { he: "סחתיין! אתה מקסים כמו עוגת שוקולד!", en: "Sachteyn! ata maksim kmo ugat shokolad!" },
    { he: "מלך! אתה שולט כמו מלך האריות!", en: "Melech! ata sholet kmo melech ha'ariyot!" },
    { he: "מטורף! אתה לומד כמו ספוג קסום!", en: "Metoraf! ata lomed kmo sfog kasum!" },
    { he: "כל הכבוד! אתה פותר כמו בלש מנוסה!", en: "Kol hakavod! ata pater kmo balash menuse!" },
    { he: "גאוני! אתה חכם כמו מדען במעבדה!", en: "Ga'oni! ata chacham kmo mada'an bama'abada!" },
    { he: "וואו! אתה מתקדם כמו ענן בשמיים!", en: "Wow! ata mitkadem kmo anan bashamayim!" },
    { he: "איזה אלוף! אתה עונה כמו הד מדויק!", en: "Eize aluf! ata oneh kmo hed meduyak!" },
    { he: "מעולה! אתה זוהר כמו זהב טהור!", en: "Me'ule! ata zohar kmo zahav tahor!" },
    { he: "פצצה! אתה חד כמו להב חדש!", en: "Ptzatza! ata chad kmo lahav chadash!" },
    { he: "יאללה! עוד ניצחון ואתה בהיסטוריה!", en: "Yalla! od nitzachon ve'ata bahistoria!" },
    { he: "אלוף! אתה מחזיק ראש כמו מלך!", en: "Aluf! ata machzik rosh kmo melech!" },
    { he: "מדהים! אתה מהיר כמו סנאי על עץ!", en: "Madhim! ata mahir kmo snai al etz!" },
    { he: "כל הכבוד! אתה ממשיך כמו מפל מים!", en: "Kol hakavod! ata mamshich kmo mapal mayim!" },
    { he: "וואו! אתה נוצץ כמו קריסטל!", en: "Wow! ata notzetz kmo kristal!" },
    { he: "מושלם! אתה מדויק כמו טייס במטוס!", en: "Mushlam! ata meduyak kmo tayas bamatos!" },
    { he: "חזק! אתה איתן כמו עץ אלון!", en: "Chazak! ata eitan kmo etz alon!" },
    { he: "אשש! אתה ערמומי כמו שועל במשל!", en: "Ash! ata armumi kmo shual bemashal!" },
    { he: "בום! אתה מפוצץ את כל השיאים!", en: "Bum! ata mefutzatz et kol hashi'im!" },
    { he: "גדול! אתה כוכב כמו שחקן ראשי!", en: "Gadol! ata kochav kmo sachkan rashi!" },
    { he: "סחתיין! אתה מקסים כמו בובה עם חיוך!", en: "Sachteyn! ata maksim kmo buba im chiyuch!" },
    { he: "מלך! אתה שולט כמו אלוף אולימפי!", en: "Melech! ata sholet kmo aluf olimpi!" },
    { he: "מטורף! אתה לומד כמו מכונת למידה!", en: "Metoraf! ata lomed kmo mechonat lemida!" },
    { he: "כל הכבוד! אתה פותר כמו מתמטיקאי!", en: "Kol hakavod! ata pater kmo matematikai!" },
    { he: "גאוני! אתה חכם כמו מוח עם מנוע!", en: "Ga'oni! ata chacham kmo moach im manoa!" },
    { he: "וואו! אתה מתקדם כמו עפיפון ברוח!", en: "Wow! ata mitkadem kmo afifon baruach!" },
    { he: "איזה אלוף! אתה עונה כמו תוף מתוק!", en: "Eize aluf! ata oneh kmo tof matok!" },
    { he: "מעולה! אתה זוהר כמו כוכב בים!", en: "Me'ule! ata zohar kmo kochav bayam!" },
    { he: "פצצה! אתה חד כמו קרן לייזר!", en: "Ptzatza! ata chad kmo keren laizer!" },
    { he: "יאללה! עוד אות ואתה אגדה!", en: "Yalla! od ot ve'ata agada!" },
    { he: "אלוף! אתה מחזיק מעמד כמו גיבור!", en: "Aluf! ata machzik ma'amad kmo gibor!" },
    { he: "מדהים! אתה מהיר כמו שדון קטן!", en: "Madhim! ata mahir kmo shadon katan!" },
    { he: "כל הכבוד! אתה סופר-כוכב של אותיות!", en: "Kol hakavod! ata super-kochav shel otiot!" }
  ];
